FROM node:16-alpine

ENV BACKEND_URL=http://0.0.0.0:4000

ADD frontend /app

WORKDIR /app

RUN npm install

ENTRYPOINT [ "npm" ]

CMD ["start"]


# WORKDIR /app

# COPY Frontend/package*.json .

# RUN npm install

# COPY Frontend/ .

# CMD ["npm", "start"]